# Generated by Django 4.0.4 on 2022-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.UUIDField(null=True)),
                ('country_name', models.CharField(max_length=100, null=True)),
                ('city_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
