# Generated by Django 4.0.4 on 2022-05-15 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_sensor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperature_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('sensor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
        ),
    ]
