# Generated by Django 4.0.4 on 2022-05-15 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_id',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='city_name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[ ]*[a-z][a-z]*$', 'Only lower case letters allowed.')]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='country_name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[ ]*[a-z][a-z]*$', 'Only lower case letters allowed.')]),
        ),
    ]
