# Generated by Django 4.0.4 on 2022-05-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_remove_sensor_sensor_id_alter_sensor_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
