# Generated by Django 4.0.4 on 2022-05-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_remove_sensordata_temperature_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data_all', to='sensors.sensor'),
        ),
    ]
