# Generated by Django 4.0.4 on 2022-05-19 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_alter_sensordata_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='city_name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-z\\s]+$', 'Only lower case letters allowed.')]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='country_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-z\\s]+$', 'Only lower case letters allowed.')]),
        ),
    ]
